export const GET_HOME_TEXTS_REQUEST = 'GET_HOME_TEXTS_REQUEST';
export const GET_HOME_TEXTS_SUCCESS = 'GET_HOME_TEXTS_SUCCESS';
export const GET_HOME_TEXTS_FAIL = 'GET_HOME_TEXTS_FAIL';

export const GET_CAREER_TEXTS_REQUEST = 'GET_CAREER_TEXTS_REQUEST';
export const GET_CAREER_TEXTS_SUCCESS = 'GET_CAREER_TEXTS_SUCCESS';
export const GET_CAREER_TEXTS_FAIL = 'GET_CAREER_TEXTS_FAIL';

export const GET_ABOUT_TEXTS_REQUEST = 'GET_ABOUT_TEXTS_REQUEST';
export const GET_ABOUT_TEXTS_SUCCESS = 'GET_ABOUT_TEXTS_SUCCESS';
export const GET_ABOUT_TEXTS_FAIL = 'GET_ABOUT_TEXTS_FAIL';

export const GET_NAVBAR_REQUEST = 'GET_NAVBAR_REQUEST';
export const GET_NAVBAR_SUCCESS = 'GET_NAVBAR_SUCCESS';
export const GET_NAVBAR_FAIL = 'GET_NAVBAR_FAIL';

export const GET_FOOTER_REQUEST = 'GET_FOOTER_REQUEST';
export const GET_FOOTER_SUCCESS = 'GET_FOOTER_SUCCESS';
export const GET_FOOTER_FAIL = 'GET_FOOTER_FAIL';

export const GET_HOME_IMAGES_REQUEST = 'GET_HOME_IMAGES_REQUEST';
export const GET_HOME_IMAGES_SUCCESS = 'GET_HOME_IMAGES_SUCCESS';
export const GET_HOME_IMAGES_FAIL = 'GET_HOME_IMAGES_FAIL';

export const GET_LANGUAGES_LIST_REQUEST = 'GET_LANGUAGES_LIST_REQUEST';
export const GET_LANGUAGES_LIST_SUCCESS = 'GET_LANGUAGES_LIST_SUCCESS';
export const GET_LANGUAGES_LIST_FAIL = 'GET_LANGUAGES_LIST_FAIL';
